### ISSUE TITLE
visualize til validate

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-eman2#11]
If you run the test: testEmanTiltValidate

and select analize for tilt-validate
you get the error

Scipion v2.0 (2018-11-27) Diocletian (jmrt-em-refactor b5267d900b)

>>>>> python  /home/marta/software/scipion_plugin/pyworkflow/apps/pw_manager.py 
Can't report usage:  'str' object has no attribute 'values'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/marta/software/scipion_plugin/pyworkflow/gui/form.py", line 972, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/marta/software/scipion_plugin/pyworkflow/viewer.py", line 314, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/eman2/viewers.py", line 733, in _showPlot
    raise Exception("Contour plot file not found: %s" % plotFn)
Exception: Contour plot file not found: Runs/000278_EmanProtTiltValidate/extra/TiltValidate_01/contour.hdf

**Comment by azazellochg** [comment]
Contour plot is not generated by default in the protocol, you need to select this advanced option. Main output is scatter plot.
