### ISSUE TITLE
Analyze Results in TestEmanTiltValidate

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-eman2#32]
Related to PR #31:

When analyzing results of 'eman2-tilt validate' procotol:
* Error in the contour plot (see Error 1)
* Error in the when visualizing scatter plot with Eman (see Error2)

For error1, I found a related issue #11, but I think the viewer should show an info message saying that this option is not available with the selected parameters of the protocol run.

```
Error 1 (after contour plot)
>>>>> python  /home/josem/work/development/scipion/v2.0.0/pyworkflow/apps/pw_project.py "TestEmanTiltValidate"
PROJECT: Warning, protocol view 'None' not found.
         Using 'Protocols SPA' instead.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/josem/work/development/scipion/v2.0.0/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/gui/form.py", line 1207, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/viewer.py", line 314, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/josem/work/development/scipion/plugins/scipion-em-eman2/eman2/viewers.py", line 747, in _showPlot
    raise Exception("Contour plot file not found: %s" % plotFn)
Exception: Contour plot file not found: Runs/000282_EmanProtTiltValidate/extra/TiltValidate_01/contour.hdf
```
```
Error 2 (after scatter plot with Eman)
INFO /home/josem/work/development/scipion/v2.0.0/software/em/eman-2.3/bin/e2tiltvalidate.py  --path=TiltValidate_01 --radcut=45.00 --gui --planethres=360.00
Couldn't load tp from DB, not showing polar plot
Couldn't open contour plot
Traceback (most recent call last):
  File "/home/josem/work/development/scipion/v2.0.0/software/em/eman-2.3/bin/e2tiltvalidate.py", line 591, in <module>
    main()
  File "/home/josem/work/development/scipion/v2.0.0/software/em/eman-2.3/bin/e2tiltvalidate.py", line 110, in main
    display_validation_plots(options.path, options.radcut, options.planethres, plotdatalabels=options.datalabels, color=options.datalabelscolor, plotzaxiscolor=options.colorzaxis)
  File "/home/josem/work/development/scipion/v2.0.0/software/em/eman-2.3/bin/e2tiltvalidate.py", line 490, in display_validation_plots
    plot = EMValidationPlot()
UnboundLocalError: local variable 'EMValidationPlot' referenced before assignment
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/josem/work/development/scipion/v2.0.0/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/gui/form.py", line 1207, in _visualizeVar
    self.visualizeCallback(self.paramName)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/viewer.py", line 314, in _visualizeParam
    views = self._getVisualizeDict()[paramName](paramName)
  File "/home/josem/work/development/scipion/plugins/scipion-em-eman2/eman2/viewers.py", line 783, in _showEmanPlot
    numberOfMpi=1, numberOfThreads=1)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/protocol/protocol.py", line 1311, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/protocol/executor.py", line 70, in runJob
    env=env, cwd=cwd, gpuList=self.getGpuList())
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/utils/process.py", line 52, in runJob
    return runCommand(command, env, cwd)
  File "/home/josem/work/development/scipion/v2.0.0/pyworkflow/utils/process.py", line 67, in runCommand
    env=env, cwd=cwd)
  File "/home/josem/work/development/scipion/v2.0.0/software/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/josem/work/development/scipion/v2.0.0/software/em/eman-2.3/bin/e2tiltvalidate.py  --path=TiltValidate_01 --radcut=45.00 --gui --planethres=360.00' returned non-zero exit status 1
```

**Comment by azazellochg** [comment]
Thanks, I'll make an info message for 1.  2 is a bug in Eman 2.3,to be fixed

**Comment by delarosatrevin** [comment]
Should then we disable option 2 until fixed?
